### ISSUE TITLE
Permission denied during start

### ISSUE THREAD

**Issue by IgorEBatista** [JonathanPrexl/SenPa-MAE#1]
I was trying to run the model and for the command `bash start_container.sh` I get these errors:

- `permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`
- `docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock:`

When dealing with the problem, I tried to use `sudo` , and it installed the dependencies, but I got another two errors:

- `Step 27/33 : RUN useradd user -u $HOST_UID
 ---> Running in bdae1630f14b
useradd: UID 0 is not unique
The command '/bin/sh -c useradd user -u $HOST_UID' returned a non-zero code: 4`

- `Unable to find image 'jp/senpamae:latest' locally
docker: Error response from daemon: pull access denied for jp/senpamae, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

What do I need to do to overcome these errors?

**Comment by JonathanPrexl** [comment]
Is your user a member of the docker group? Alternatively, you can also work outside of a docker container when you have any running pytorch installation there (all other necessary liberties you find listed in the dockerfile).

**Comment by IgorEBatista** [comment]
Thanks!
